name: Documentation improvement
description: Suggest improvements to documentation.
labels: [documentation]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a documentation improvement, please make sure it hasn't been already
      addressed by searching through [the past issues](https://github.com/pi-optimal/pi-optimal/issues).

- type: textarea
  attributes:
    label: What needs improvement?
    description: >
      Describe which documentation needs to be improved. Please include links to the current documentation if possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggested changes
    description: >
      Describe your suggested changes or additions. If possible, provide examples of the improved documentation.
  validations:
    required: false
- type: textarea
  attributes:
    label: Why is this important?
    description: >
      Explain why this documentation improvement matters and who would benefit from it.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!